<?php

namespace ContainerWfxyhYz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N5b1g05Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n5b1g05' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n5b1g05'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactMessage' => ['privates', '.errored..service_locator.n5b1g05.App\\Entity\\ContactMessage', NULL, 'Cannot autowire service ".service_locator.n5b1g05": it references class "App\\Entity\\ContactMessage" but no such service exists.'],
        ], [
            'contactMessage' => 'App\\Entity\\ContactMessage',
        ]);
    }
}
