<?php

namespace ContainerWfxyhYz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.n5b1g05.App\Entity\ContactMessage' shared service.
     *
     * @return \App\Entity\ContactMessage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.n5b1g05": it references class "App\\Entity\\ContactMessage" but no such service exists.');
    }
}
