<?php

namespace Container42Bu4VR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZCeWfwAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zCeWfwA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zCeWfwA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactMessageRepository' => ['privates', 'App\\Repository\\ContactMessageRepository', 'getContactMessageRepositoryService', true],
        ], [
            'contactMessageRepository' => 'App\\Repository\\ContactMessageRepository',
        ]);
    }
}
