<?php

namespace Container42Bu4VR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lc39rgZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lc39rgZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lc39rgZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService', true],
            'repoType' => ['privates', 'App\\Repository\\TypeRepository', 'getTypeRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\VideoRepository',
            'repoType' => 'App\\Repository\\TypeRepository',
        ]);
    }
}
