<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWfxyhYz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWfxyhYz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWfxyhYz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWfxyhYz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWfxyhYz\App_KernelDevDebugContainer([
    'container.build_hash' => 'WfxyhYz',
    'container.build_id' => 'd9c8997b',
    'container.build_time' => 1634530004,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWfxyhYz');
